#mysql设置
spring:
  datasource:
    url: jdbc:mysql://www.meet0208.icu:30336/gift_shop?useUnicode=true&characterEncode=utf-8
    username: root
    password: Resu@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: www.meet0208.icu
    port: 26379
    password: admin@111
    database: 5
    timeout: 1800000
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    mapper:
      default-view-inclusion: true

hibernate:
  hbm2ddl:
    auto: update
